
springdoc:
  packagesToScan: com.github.murilonerdx.cineminha.controller
  swagger-ui:
    path: /docs-cineminha-service.html
  api-docs:
    path: /docs-cineminha-service

spring:
  application:
    name: cineminha-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cineminha-service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}

    initialize: true
    maxActive: 3
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1